"""merge msg status to messages;

Revision ID: a1ab2d006923
Revises: 
Create Date: 2022-07-31 15:58:49.597179

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1ab2d006923"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("replied", sa.Boolean(), nullable=True))
    op.add_column("messages", sa.Column("sent_to_rum", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "sent_to_rum")
    op.drop_column("messages", "replied")
    # ### end Alembic commands ###
